[package]
name = "async_smux"
version = "0.1.4"
authors = ["black-binary <blackbinary@qq.com>"]
description = "Asynchronous smux library for smol / async-std"
license = "MIT"
edition = "2018"

[dependencies]
futures = "0.3"
bytes = "0.6"
rand = "0.7"
log = "0.4"
smol = "1"

[dev-dependencies]
smol = "1"
async-std = "1"
bytes = "0.6"
env_logger = "0.8"
criterion = "0.3"

[profile.release]
debug = true

[[bench]]
name = "bench_smux"
harness = false